const items = [
  {
    id: 0,
    name: "cheese",
    value: 1,
    type: "food",
    hp: 7,
    desc: "",
  },
  {
    id: 1,
    name: "napkin",
    value: 0,
    type: "food",
    hp: -3,
    desc: "",
  },
  {
    id: 2,
    name: "wine",
    value: 5,
    type: "food",
    hp: 10,
    desc: "a bright green bottle of sherry wine, neatly wrapped in a wicker sleeve, tied to the neck is a small piece of paper that reads: 'Good luck on your quest! -love and kisses; Gandalf'",
  },
  {
    id: 3,
    name: "worm",
    value: 1,
    type: "food",
    hp: 1,
    desc: "",
  },
  {
    id: 4,
    name: "shortsword",
    value: 30,
    type: "weapon",
    damage: 12,
    desc: "",
  },
  {
    id: 5,
    name: "beetle shell fragment",
    value: 3,
    type: "material",
    desc: "",
  },
  {
    id: 6,
    name: "beetle resin",
    value: 2,
    type: "material",
    desc: "",
  },
  {
    id: 7,
    name: "bone shards",
    value: 0,
    type: "material",
    desc: "",
  },
];

exports.items = items;
